GET http://localhost:3004/api/persons

###
GET http://localhost:3004/info

###
DELETE http://localhost:3004/api/persons/80

###
POST http://localhost:3004/api/persons
Content-Type: application/json

{
     "name":"bunny",
     "number":"098766555"
    

} 

###
PUT  http://localhost:3004/api/persons/64cc6c450db43206c8fe55aa
Content-Type: application/json

{
     "name":"this",
     "number":"1000"
    

} 