GET http://localhost:3004/api/persons

###
GET http://localhost:3004/api/persons/64cf28cf773d212572093239

###
GET http://localhost:3004/info

###
DELETE http://localhost:3004/api/persons/80

###
POST http://localhost:3004/api/persons
Content-Type: application/json

{
     "name":"bu",
     "number":"098766555"
    

} 

###
PUT  http://localhost:3004/api/persons/64cf28cf773d212572093239
Content-Type: application/json

{
     "name":"sugam",
     "number":"0"
    

} 