GET http://localhost:3004/api/persons

###
GET http://localhost:3004/info

###
DELETE http://localhost:3004/api/persons/1

###
POST http://localhost:3004/api/persons
Content-Type: application/json

{
    "name":"pratiksha",
    "number":"098776555"

}