GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/user


###
POST http://localhost:3001/api/notes
Content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxheG1pIiwiaWQiOjEsImlhdCI6MTY5NjIxNzkxMH0.-own_uCits8qf6mCorflEB6g2wQWQARY4wwcvBKnsD4

{
"content": "new blog with testing with another from laxmi",
"important":"false"

}

###
POST http://localhost:3001/api/users
Content-type: application/json

{
"username": "usha",
"name":"123"


}

###
PUT http://localhost:3001/api/users/laxmi
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxheG1pIiwiaWQiOjEsImlhdCI6MTY5NjIxOTg2MX0.J4EBBbg7_j0H-hny0p9WnpYngDs0RSOgnZhrWYsi-R0

{
"disabled":false


}


###
POST http://localhost:3001/api/login
Content-type: application/json

{
"username": "laxmi",
"password":"secret"

}
###
PUT http://localhost:3001/api/notes/1
Content-type: application/json

{
"content": "winter is coming again",
"important":"false"

}