GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/users


###
POST http://localhost:3001/api/notes
Content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYXRpa3NoYSIsImlkIjo0LCJpYXQiOjE2OTYzNDg1ODV9.c9uXxsewkMLzPIqukJr_A_Ft_Fdgkx9JmTq8y8QPa8w

{
"content": "new blog with testing with another from pratiksha second",
"important":"false"

}

###
POST http://localhost:3001/api/users
Content-type: application/json

{
"username": "pratiksha",
"name":"123"


}

###
PUT http://localhost:3001/api/users/usha
Content-type: application/json
//Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxheG1pIiwiaWQiOjEsImlhdCI6MTY5NjIxOTg2MX0.J4EBBbg7_j0H-hny0p9WnpYngDs0RSOgnZhrWYsi-R0

{
"disabled":"false"


}


###
POST http://localhost:3001/api/login
Content-type: application/json

{
"username": "pratiksha",
"password":"secret"

}
###
PUT http://localhost:3001/api/notes/1
Content-type: application/json

{
"content": "winter is coming again",
"important":"false"

}