GET http://localhost:3001/api/notes

###
DELETE http://localhost:3001/api/notes/64e1ce889b5c4e2589c2e6c4
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxheG1pIiwiaWQiOiI2NGUxYTUxOWVkNjQ3NzRmOWEwYWRkM2YiLCJpYXQiOjE2OTI1MjAwMjd9.PG2tY-53dYMlLVzl2aCmITo-F3EFJas2tE0-QeT3xwI

###
POST http://localhost:3001/api/notes
Content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxheG1pIiwiaWQiOiI2NGUxYTUxOWVkNjQ3NzRmOWEwYWRkM2YiLCJpYXQiOjE2OTI1MjAwMjd9.PG2tY-53dYMlLVzl2aCmITo-F3EFJas2tE0-QeT3xwI

{
 "content":"1hellow New note from the loggedIn user",
 "important":false
 
}

###
POST http://localhost:3001/api/users
Content-type: application/json

{
"username":"laxmi",
"name":"laxmi",
"password":"123"
   
   }

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/login
Content-type: application/json

{
"username":"laxmi",
"password":"123"
   
}

###
PUT  http://localhost:3001/api/notes/64e1aa13bab2e4b8123d4d25
Content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxheG1pIiwiaWQiOiI2NGUxYTUxOWVkNjQ3NzRmOWEwYWRkM2YiLCJpYXQiOjE2OTI1MjAwMjd9.PG2tY-53dYMlLVzl2aCmITo-F3EFJas2tE0-QeT3xwI

{
"content": "New note from the loggedIn user",
"important": true
   
}