GET http://localhost:3001/api/notes

###
DELETE http://localhost:3001/api/notes/64cb47e06f92df2a50fa70db

###
POST http://localhost:3001/api/notes
Content-type: application/json

{
 "content":"third New note from the loggedIn user",
 "important":false,
 "userId":"64e1a4fbed64774f9a0add3d" 
}

###
POST http://localhost:3001/api/users
Authorizaton: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxheG1pIiwiaWQiOiI2NGUxYTUxOWVkNjQ3NzRmOWEwYWRkM2YiLCJpYXQiOjE2OTI1MTUzODJ9.otONES5uHmzyfvITsrVx3xEhGdSvDDA6rxGr8eL_3Pg
Content-type: application/json

{
"username":"laxmi",
"name":"laxmi",
"password":"123"
   
   }

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/login
Content-type: application/json

{
"username":"laxmi",
"password":"123"
   
}