GET http://localhost:3001/api/notes

###
DELETE http://localhost:3001/api/notes/64cb47e06f92df2a50fa70db

###
POST http://localhost:3001/api/notes
Content-type: application/json

{
 "content":"sam",
 "important":false   
}