GET http://localhost:3002/api/blogs

###
POST http://localhost:3002/api/blogs
Content-type: application/json

{
 "title":"jananpur",
 "author":"sam" ,
 "url": "www.kathmandupost.com",
 "likes":41
 

}

###
DELETE  http://localhost:3002/api/blogs/64d4b9c9121608415beea9dd


###
PUT  http://localhost:3002/api/blogs/64d30de9e64b43122d73b3c6
Content-type: application/json

{
"title": "landSlide",
"author": "sam",
"url": "www.kathmandupost.com",
"likes": 7
 }

