GET http://localhost:3002/api/blogs

###
POST http://localhost:3002/api/blogs
Content-type: application/json
Authorization: Bearer 

{
 "title":"manipur",
 "author":"usha" ,
 "url": "www.kathmandupost.com"
 
 }

###
DELETE  http://localhost:3002/api/blogs/64d4b9c9121608415beea9dd


###
PUT  http://localhost:3002/api/blogs/64d30de9e64b43122d73b3c6
Content-type: application/json

{
"title": "landSlide",
"author": "sam",
"url": "www.kathmandupost.com",
"likes": 7
 }

###
POST http://localhost:3002/api/users
Content-type: application/json

{
 "username":"usha",
 "name":"usha",
 "password": "123"
 
 }

###
 GET http://localhost:3002/api/users


###
POST http://localhost:3002/api/login
Content-type: application/json

{
 "username":"usha",
 "password":"123"
 
 }