GET http://localhost:3002/api/blogs

###
POST http://localhost:3002/api/blogs
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzaGEiLCJpZCI6IjY0ZDg2OGRkYzBmYjFmZjc2NWY4NWJhNiIsImlhdCI6MTY5MTkxNTYyM30.0nPxjBDbtYjCxiasPPrpJgKIJH7mUdVSZ9QPNitngz0

{
 "title":"manipur",
 "author":"usha" ,
 "url": "www.kathmandupost.com"
 
 }

###
DELETE  http://localhost:3002/api/blogs/64d891eea7a3dd11a7b365da
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzaGEiLCJpZCI6IjY0ZDg2OGRkYzBmYjFmZjc2NWY4NWJhNiIsImlhdCI6MTY5MTkxNTYyM30.0nPxjBDbtYjCxiasPPrpJgKIJH7mUdVSZ9QPNitngz0


###
PUT  http://localhost:3002/api/blogs/64d30de9e64b43122d73b3c6
Content-type: application/json

{
"title": "landSlide",
"author": "sam",
"url": "www.kathmandupost.com",
"likes": 7
 }

###
POST http://localhost:3002/api/users
Content-type: application/json

{
 "username":"usha",
 "name":"usha",
 "password": "123"
 
 }

###
 GET http://localhost:3002/api/users


###
POST http://localhost:3002/api/login
Content-type: application/json

{
 "username":"usha",
 "password":"123"
 
 }